version: 2

job_defaults: &job_defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        CHROME_BIN: '/usr/bin/google-chrome'
  working_directory: ~/project/repo

#app
cache_key: &cache_key pages-app-deps-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
dist_key: &dist_key pages-app-dist-{{ .Revision }}

#pages dist package
cache_pages_key: &cache_pages_key pages-deps-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
dist_pages_key: &dist_pages_key pagess-dist-{{ .Revision }}

jobs:
  install:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: install-dependencies
          command: npm ci
      - run:
          name: Install Semantic Release globally
          command: sudo npm i -g semantic-release@15
      - run:
          name: Install resync command
          command: sudo apt install rsync
      - save_cache:
          key: *cache_key
          paths:
            - node_modules

  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: lint
          command: npm run lint

  test-app:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run:
          name: test
          command: npm run test

  build-library:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Install resync command
          command: sudo apt install rsync
      - run:
          name: build @angular-material-extensions/pages library
          command: cd projects/angular-material-extensions/pages && npm run build
      - save_cache:
          key: *dist_pages_key
          paths:
            - dist/angular-material-extensions/pages

  build-prerender-app:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_pages_key
      - run:
          name: check dist files
          command: ls projects/angular-material-extensions/pages/
      - run:
          name: link library
          command: npm run link
      - run:
          name: build-prerender
          command: sudo npm run build:prerender
      - save_cache:
          key: *dist_key
          paths:
            - dist

  release-app:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run:
          name: release-app
          command: npm run semantic-release || true

  release-pages-lib:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_pages_key
      - run:
          name: release-pages-lib
          command: cd projects/angular-material-extensions/pages && npx semantic-release || true

  deploy-app-dev:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run:
          name: deploy-app-dev
          command: npm run deploy:gh

workflows:
  version: 2
  build-test-release:
    jobs:
      - install
      #      - lint:
      #          requires:
      #            - install
      #      - test-app:
      #          requires:
      #            - install
      - build-library:
          requires:
            - install
      - build-prerender-app:
          requires:
            - build-library
      #            - test-app
      - release-pages-lib:
          requires:
            - build-library
          filters:
            branches:
              only: pages
      - release-app:
          requires:
            - build-prerender-app
          filters:
            branches:
              only: master
      - deploy-app-prod:
          requires:
            - release-app
          filters:
            branches:
              only: master
#      - deploy-app-dev:
#          requires:
#            - build-prerender-app
#          filters:
#            branches:
#              only: dev
